unit UTestImpressoraFiscal;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, Windows, Forms, Dialogs, Controls, Classes, ExtCtrls, SysUtils, Variants,
  Graphics, StdCtrls, Messages, UVendaProduto, UVendaProdutoMuka, UVendaProdutoBase,
  UFabricaVendaProduto;

type
  // Test methods for class TFrmMain



  TestImpressoraFiscal = class(TTestCase)
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestVendaDeProduto;
  end;

implementation

{ TestImpressoraFiscal }

procedure TestImpressoraFiscal.SetUp;
begin
  inherited;

end;

procedure TestImpressoraFiscal.TearDown;
begin
  inherited;

end;

procedure TestImpressoraFiscal.TestVendaDeProduto;
var venda : TVendaProdutoBase;
begin
  venda := TFabricaVendaProduto.CriaVendaProduto(tiPadrao);
  CheckTrue(venda.adiciona('Descrição', 23, 49.90), 'erro ao adicionar produto');

  venda := TFabricaVendaProduto.CriaVendaProduto(tiMuka);
  CheckTrue(venda.adiciona('Descrição', 23, 49.90), 'erro ao adicionar produto');

end;


initialization
  // Register any test cases with the test runner
  RegisterTest(TestImpressoraFiscal.Suite);
end.


