unit UTestDUGORM;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, UCliente;

type
  // Test methods for class TCalculadora

  TestTCalculadora = class(TTestCase)
  strict private
    FCliente: TCliente;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestPersistenciaCliente;
  end;

implementation

procedure TestTCalculadora.SetUp;
begin
  FCliente := TCliente.Create;
end;

procedure TestTCalculadora.TearDown;
begin
  FCliente.Free;
  FCliente := nil;
end;


procedure TestTCalculadora.TestPersistenciaCliente;
begin
  FCliente.Nome := 'Daniel';
  FCliente.Twitter := 'dwildt';

  CheckEquals (
    'insert into clientes (nome, twitter) values (''Daniel'', ''dwildt'');',
    FCliente.InsertCommand);

  ;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTCalculadora.Suite);
end.

